stages:
  - deploy

deploy_to_production:
  stage: deploy
  only:
    - master
  script:
    - cd /home/ubuntu/form-submission
    - sudo git pull origin master
    - sudo docker compose build api
    - sudo docker compose up -d
